In [1]:
import numpy as np
import pandas as pd
from sklearn.manifold import TSNE

In [2]:
df = pd.read_parquet('processed/combined.parquet')

In [3]:
df

,ID,Resume_str,Resume_html,Category,extracted_skills,length,matched_skills,matched_skills_ordered,skill_embeddings,skill_embeddings_ordered,avg_skill_embedding,best_match_index,best_match_score,best_match_job_embedding,best_match_job_skills,true_missing,difference,predicted_missing,predicted_missing_id,predicted_missing_embedding
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR,"[Accounting, Ads, Advertising, Analytical skil...",5442,"[accounting, create advertisements, outdoor ad...","[accounting, company policies, conduct public ...","[-0.051119804, 0.051380936, -0.1956489, -0.000...","[-0.028823888, 0.056566164, -0.19899392, -0.00...","[0.0002473207458333337, 0.03493942622916666, -...",17293,0.780933,"[-0.019919312, 0.023642017, -0.2060649, 0.0192...","[align efforts towards business development, c...","[sales strategies, communication, align effort...","[0.008904575999999997, -0.032924147, -0.007070...","[align efforts towards business development, c...",2093,"[-0.027203888, -0.011654166, -0.17698255, 0.02..."
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR,"[Adobe Photoshop, ADP, Asset Management, brand...",5572,"[Adobe Photoshop, asset management, maintain c...","[Adobe Illustrator, Adobe Photoshop, asset man...","[-0.013715399, 0.01982399, -0.15967667, 0.0198...","[-0.02063493, 0.030683268, -0.16921557, 0.0126...","[0.002284706435294118, 0.01609132022352941, -0...",2643,0.920584,"[-0.022659931, 0.050614443, -0.14851327, 0.019...","[Adobe Illustrator, Adobe Photoshop, adobe cre...","[adobe creative suite, execute email marketing...","[-0.002025001000000002, 0.019931175000000002, ...","[e-commerce systems, mobile marketing, use mic...",10467,"[-0.01584606, 0.048069965, -0.16418055, 0.0358..."
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR,"[Recruiting, FMLA/EEO/FLSA, HRIS Development, ...",7720,"[recruit members, foreign affairs policy devel...","[Microsoft Access, desktop publishing, foreign...","[-0.037161566, 0.0036097213, -0.19848743, -0.0...","[0.0076125017, 0.01415186, -0.17561796, -0.009...","[-0.0002954738888888898, 0.02081807622222222, ...",4231,0.854974,"[-0.0027506491, -0.0071693026, -0.17715265, 0....","[Microsoft Access, Microsoft Visio, communicat...","[Microsoft Visio, perform political negotiatio...","[-0.0103631508, -0.0213211626, -0.001534690000...","[Microsoft Visio, communication, perform data ...",6169,"[0.043393716, -0.011427665, -0.18113784, 0.039..."
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR,"[Type 50 wpm and 10-Key by touch, Microsoft pr...",2855,"[personnel management, customer service, resol...","[customer service, personnel management, resol...","[-0.004071229, -0.0062129777, -0.16848274, -0....","[-0.0024955925, -0.005882781, -0.17091864, -0....","[0.007837255066666667, 0.0018740463333333332, ...",17897,0.823621,"[-0.01969163, -0.0019332409, -0.19000582, 0.02...","[communication, conflict management, customer ...","[communication, conflict management, manage ma...","[-0.0171960375, 0.0039495401, -0.0190871799999...","[develop outreach training plans, oversee prom...",5535,"[-0.022586903, 0.051901877, -0.18123034, 0.012..."
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR,"[ADA, ADP, art, agency, benefits, Benefits Adm...",9172,"[create artwork, coaching techniques, coaching...","[Microsoft Access, Microsoft Visio, coaching t...","[0.008319367, 0.02057786, -0.17201392, 0.01393...","[4.8317004e-05, 0.005026085, -0.17149556, 0.01...","[0.00895575635652174, 0.013967274808695652, -0...",4231,0.912354,"[-0.0027506491, -0.0071693026, -0.17715265, 0....","[Microsoft Access, Microsoft Visio, communicat...","[perform political negotiation, communication,...","[-0.002798966104, -0.0121953876, -0.0056570900...","[Cisco, communication, prepare presentation ma...",1891,"[-0.008492585, 0.01829961, -0.14708278, -0.023..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2479,99416532,RANK: SGT/E-5 NON- COMMISSIONED OFFIC...,"<div class=""fontsize fontface vmargins hmargin...",AVIATION,"[Secret Clearance, Stock Control, Management, ...",5533,"[follow stock control instructions, operations...","[communication, follow stock control instructi...","[0.0049826736, 0.0045687603, -0.19545835, -0.0...","[0.0075103026, -0.0060989116, -0.19636096, -0....","[0.007711735449999999, 0.005379060733333334, -...",5419,0.806201,"[0.0022090778, 0.037456203, -0.17540114, -0.02...","[communication, leadership principles, manage ...","[shape corporate culture, perform political ne...","[-0.0053012248000000005, 0.0435551146, 0.02095...","[communication, leadership principles, manage ...",5419,"[0.0022090778, 0.037456203, -0.17540114, -0.02..."
2480,24589765,"GOVERNMENT RELATIONS, COMMUNICATIONS ...","<div class=""fontsize fontface vmargins hmargin...",AVIATION,"[arbitration, agency, budgets, Budget, continu...",7108,"[examine budgets, update budget, continuous im...","[Microsoft Visio, computer graphics, continuou...","[0.04153785, 0.038161203, -0.16648234, -0.0115...","[0.048209656, 0.025236994, -0.15883973, -0.005...","[0.013527077672727272, 0.028311003981818184, -...",2181,0.868528,"[0.0048152753, 0.035498492, -0.1639306, 0.0078...","[Microsoft Visio, architectural design, commun...","[improve business processes, communication, ri...","[-0.0433943807, 0.010261498, -0.00509086999999...","[Microsoft Visio, architectural design, commun...",2181,"[0.0048152753, 0.035498492, -0.1639306, 0.0078..."
2481,31605080,GEEK SQUAD AGENT Professional...,"<div class=""fontsize fontface vmargins hmargin...",AVIATION,"[Active Directory, Hardware, Customer Service,...",2020,"[hardware materials, customer service, manage ...","[assemble windows, customer service, hardware ...","[0.010476048, 0.028934365, -0.16972545, 0.0036...","[0.010129859, 0.025989288, -0.16765723, 0.0025...","[0.025738319725, 0.032416258287500006, -0.1611...",19777,0.895933,"[0.032687627, -0.031283237, -0.15812683, -0.02...","[assemble windows, communication, customer ser...","[project management, perform data analysis, id...","[0.022557768, -0.057272525, 0.0095303999999999...","[communication, identify process improvements,...",6957,"[0.038275912, -0.04439795, -0.12975419, -0.030..."
2482,21190805,PROGRAM DIRECTOR / OFFICE MANAGER ...,"<div class=""fontsize fontface vmargins hmargin...",AVIATION,"[Adobe, CPR, Customer Service, Customer Care, ...",5074,"[customer service, maintain customer service, ...","[Microsoft Access, chair a meeting, customer s...","[-0.013092378, 0.055586472, -0.17801957, -0.01...","[-0.006703326, 0.049669117, -0.16404499, -0.01...","[-0.003938775142857142, 0.026151056, -0.158061...",18145,0.863478,"[0.020848472, 0.0077196537, -0.16200365, -0.00...","[Microsoft Access, communication, customer ser...","[information confidentiality, ethics, communic...","[0.027551798, -0.041949463299999996, 0.0020413...","[Microsoft Access, communication, customer ser...",18145,"[0.020848472, 0.0077196537, -0.16200365, -0.00..."
2483,37473139,STOREKEEPER II Professional Sum...,"<div class=""fontsize fontface vmargins hmargin...",AVIATION,"[Architectural Drafting, AutoCAD, Customer Ser...",5234,"[create architectural sketches, customer servi...","[advise on safety measures, advise supervisors...","[-0.036120985, 0.033106253, -0.17913961, -0.03...","[-0.021321548, 0.018513214, -0.17295599, -0.02...","[-0.0028159249666666656, 0.019260893350000002,...",190,0.825848,"[0.024227371, -0.023091564, -0.15055132, 0.006...","[communication, follow written instructions, m...","[select material to process, operate material ...","[0.045548919, -0.041604777999999995, 0.0224046...","[communication, follow written instructions, m...",190,"[0.024227371, -0.023091564, -0.15055132, 0.006..."

In [4]:
count = 0 
for index, row in df.iterrows():
    if row['best_match_index'] == row['predicted_missing_id']:
        print(index)
        count += 1

7
11
12
13
14
15
16
19
20
23
24
25
27
31
32
33
34
35
36
38
39
40
41
43
44
46
48
50
55
61
68
71
72
76
77
78
80
84
88
90
91
92
97
98
99
100
103
104
107
108
111
112
113
114
118
119
121
126
127
129
131
133
142
143
144
146
155
158
162
166
167
168
169
173
174
175
177
178
179
183
184
192
193
194
197
205
210
211
214
215
220
224
226
228
229
234
240
242
246
247
248
254
256
259
262
266
269
270
271
274
276
278
283
285
287
290
292
296
299
300
301
306
312
314
322
323
329
330
332
333
334
337
344
350
353
354
358
360
361
363
364
376
381
382
386
387
388
389
392
393
394
397
399
401
403
404
408
410
411
416
421
422
425
427
429
431
432
435
436
438
439
440
442
444
445
446
448
449
450
453
454
457
459
461
462
463
465
467
468
469
471
477
483
486
487
490
491
493
495
496
497
499
500
502
507
508
509
510
512
516
518
519
523
524
525
527
528
529
530
531
532
533
536
543
544
548
550
552
554
555
557
558
559
560
562
564
565
569
570
587
590
592
594
600
602
604
605
610
612
614
622
632
637
638
640
644
645
647
648
652
654
657
658
660
662
663
665
668
670
677
684
685
687
688
690
693
694
696
698
700
704
707
710
712
713
716
718
720
724
725
726
727
728
729
731
734
737
739
740
741
742
744
750
751
752
754
755
756
759
760
763
765
768
769
771
773
774
780
781
782
783
785
789
790
791
792
796
797
800
801
802
803
805
808
813
816
817
819
820
822
823
824
825
828
829
838
841
845
848
850
855
857
860
861
862
863
867
868
870
871
873
874
875
878
879
882
884
894
896
901
902
908
909
910
911
912
914
915
917
919
920
922
923
924
925
927
929
930
931
932
934
935
936
940
941
942
943
944
946
947
948
949
950
951
952
957
960
961
965
967
968
973
975
978
981
985
988
990
991
993
995
996
998
1006
1007
1008
1009
1010
1011
1012
1013
1015
1017
1018
1023
1027
1029
1030
1031
1038
1042
1046
1047
1048
1049
1051
1052
1055
1057
1058
1061
1062
1064
1067
1068
1072
1079
1080
1083
1086
1087
1088
1093
1095
1096
1099
1100
1103
1105
1108
1112
1113
1116
1117
1122
1123
1124
1126
1131
1134
1135
1142
1144
1146
1151
1152
1163
1164
1167
1173
1175
1183
1186
1193
1196
1197
1198
1201
1202
1204
1205
1209
1210
1214
1216
1217
1219
1220
1222
1223
1224
1229
1231
1233
1234
1237
1238
1241
1242
1244
1246
1247
1248
1250
1252
1257
1259
1266
1267
1272
1275
1280
1282
1284
1289
1293
1305
1309
1310
1311
1312
1318
1324
1325
1326
1327
1330
1331
1332
1334
1340
1345
1349
1350
1351
1352
1354
1357
1361
1362
1363
1368
1369
1370
1371
1372
1373
1375
1376
1377
1378
1379
1380
1381
1385
1390
1391
1393
1395
1396
1399
1400
1401
1409
1411
1412
1413
1414
1417
1421
1424
1427
1428
1431
1434
1436
1438
1440
1441
1443
1444
1445
1446
1447
1449
1450
1451
1452
1454
1456
1457
1458
1459
1460
1461
1462
1465
1467
1468
1469
1470
1471
1473
1474
1478
1481
1482
1483
1485
1488
1490
1493
1496
1497
1498
1502
1504
1509
1511
1512
1513
1514
1515
1520
1523
1526
1528
1533
1541
1554
1555
1560
1562
1568
1570
1574
1575
1577
1579
1581
1583
1590
1591
1597
1598
1599
1600
1601
1607
1608
1609
1611
1614
1615
1616
1617
1618
1619
1622
1623
1626
1629
1631
1632
1634
1637
1638
1639
1641
1642
1646
1647
1649
1655
1656
1660
1664
1665
1669
1670
1671
1672
1677
1680
1686
1691
1693
1695
1697
1698
1701
1703
1705
1707
1710
1711
1713
1716
1721
1722
1723
1727
1729
1730
1732
1735
1737
1744
1745
1747
1748
1750
1751
1753
1755
1758
1765
1769
1770
1771
1772
1775
1776
1779
1784
1786
1792
1794
1796
1798
1801
1805
1807
1814
1819
1820
1822
1828
1834
1836
1840
1841
1844
1846
1847
1849
1854
1855
1856
1861
1862
1863
1864
1865
1870
1872
1874
1875
1877
1879
1880
1886
1889
1890
1897
1898
1900
1903
1908
1909
1913
1922
1925
1928
1929
1930
1931
1933
1935
1937
1939
1943
1946
1947
1951
1953
1954
1956
1958
1959
1961
1965
1966
1967
1970
1971
1972
1973
1974
1978
1979
1982
1983
1986
1987
1989
1993
1995
1996
1998
1999
2002
2003
2004
2005
2006
2009
2010
2014
2015
2016
2018
2019
2024
2027
2029
2030
2032
2033
2034
2035
2038
2043
2044
2046
2050
2053
2063
2071
2078
2083
2086
2088
2091
2092
2095
2096
2101
2106
2107
2110
2116
2117
2120
2123
2129
2133
2134
2136
2137
2138
2140
2142
2146
2148
2149
2156
2157
2159
2161
2166
2167
2172
2178
2179
2181
2182
2183
2196
2198
2203
2207
2209
2213
2215
2218
2219
2224
2226
2230
2233
2244
2252
2255
2257
2268
2271
2274
2275
2276
2277
2278
2280
2281
2283
2285
2286
2287
2289
2290
2292
2293
2294
2296
2297
2303
2307
2312
2315
2319
2320
2321
2323
2325
2335
2336
2337
2340
2341
2344
2347
2350
2351
2352
2354
2355
2356
2359
2361
2363
2366
2371
2372
2379
2382
2384
2389
2390
2391
2393
2394
2395
2396
2403
2404
2405
2411
2413
2414
2416
2418
2419
2422
2424
2425
2426
2427
2429
2430
2431
2432
2434
2437
2438
2439
2441
2442
2444
2445
2446
2447
2448
2450
2451
2456
2458
2460
2461
2462
2463
2465
2467
2470
2472
2473
2475
2476
2478
2479
2480
2482
2483

In [5]:
count/len(df)

0.4114331723027375

In [6]:
skills = np.vstack(df['skill_embeddings_ordered'].values)
jobs   = np.vstack(df['best_match_job_embedding'].values)
diffs  = np.vstack(df['difference'])
predit = np.vstack(df['predicted_missing_embedding'].values)

In [7]:
X = np.vstack([skills, jobs, diffs, predit])

In [8]:
tsne = TSNE(n_components=3, perplexity=40, max_iter=2000, learning_rate='auto')

In [9]:
X_2d = tsne.fit_transform(X)

In [10]:
n = len(df)

skills_3d = X_2d[0:n]
jobs_3d   = X_2d[n:2*n]
diff_3d =   X_2d[2*n:3*n]
predit_3d = X_2d[3*n:4*n]

In [11]:
df["skill_tsne"]   = list(skills_3d)
df["job_tsne"]     = list(jobs_3d)
df['diff_tsne'] =    list(diff_3d)
df["predict_tsne"]  = list(predit_3d)

In [12]:
df

,ID,Resume_str,Resume_html,Category,extracted_skills,length,matched_skills,matched_skills_ordered,skill_embeddings,skill_embeddings_ordered,...,best_match_job_skills,true_missing,difference,predicted_missing,predicted_missing_id,predicted_missing_embedding,skill_tsne,job_tsne,diff_tsne,predict_tsne
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR,"[Accounting, Ads, Advertising, Analytical skil...",5442,"[accounting, create advertisements, outdoor ad...","[accounting, company policies, conduct public ...","[-0.051119804, 0.051380936, -0.1956489, -0.000...","[-0.028823888, 0.056566164, -0.19899392, -0.00...",...,"[align efforts towards business development, c...","[sales strategies, communication, align effort...","[0.008904575999999997, -0.032924147, -0.007070...","[align efforts towards business development, c...",2093,"[-0.027203888, -0.011654166, -0.17698255, 0.02...","[-33.039383, -10.883406, 6.2968817]","[8.721118, -41.962807, -36.749313]","[38.382977, -14.817352, 34.59224]","[5.1793623, -39.68183, -40.631123]"
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR,"[Adobe Photoshop, ADP, Asset Management, brand...",5572,"[Adobe Photoshop, asset management, maintain c...","[Adobe Illustrator, Adobe Photoshop, asset man...","[-0.013715399, 0.01982399, -0.15967667, 0.0198...","[-0.02063493, 0.030683268, -0.16921557, 0.0126...",...,"[Adobe Illustrator, Adobe Photoshop, adobe cre...","[adobe creative suite, execute email marketing...","[-0.002025001000000002, 0.019931175000000002, ...","[e-commerce systems, mobile marketing, use mic...",10467,"[-0.01584606, 0.048069965, -0.16418055, 0.0358...","[12.3123665, 34.636612, -1.6278843]","[10.967252, 40.826458, -6.0929265]","[23.240116, 9.879008, 12.6117525]","[-4.910814, 13.567756, 6.1406693]"
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR,"[Recruiting, FMLA/EEO/FLSA, HRIS Development, ...",7720,"[recruit members, foreign affairs policy devel...","[Microsoft Access, desktop publishing, foreign...","[-0.037161566, 0.0036097213, -0.19848743, -0.0...","[0.0076125017, 0.01415186, -0.17561796, -0.009...",...,"[Microsoft Access, Microsoft Visio, communicat...","[Microsoft Visio, perform political negotiatio...","[-0.0103631508, -0.0213211626, -0.001534690000...","[Microsoft Visio, communication, perform data ...",6169,"[0.043393716, -0.011427665, -0.18113784, 0.039...","[-9.295438, 46.28939, 25.735302]","[-12.552871, 43.657314, 21.314157]","[27.578716, 36.2249, 46.472336]","[-18.901455, 52.93165, 10.894365]"
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR,"[Type 50 wpm and 10-Key by touch, Microsoft pr...",2855,"[personnel management, customer service, resol...","[customer service, personnel management, resol...","[-0.004071229, -0.0062129777, -0.16848274, -0....","[-0.0024955925, -0.005882781, -0.17091864, -0....",...,"[communication, conflict management, customer ...","[communication, conflict management, manage ma...","[-0.0171960375, 0.0039495401, -0.0190871799999...","[develop outreach training plans, oversee prom...",5535,"[-0.022586903, 0.051901877, -0.18123034, 0.012...","[-9.020148, -37.249065, 7.760453]","[-5.4295783, -35.840824, 8.815218]","[27.902058, -55.70952, 33.77973]","[12.550949, -49.75966, -24.735247]"
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR,"[ADA, ADP, art, agency, benefits, Benefits Adm...",9172,"[create artwork, coaching techniques, coaching...","[Microsoft Access, Microsoft Visio, coaching t...","[0.008319367, 0.02057786, -0.17201392, 0.01393...","[4.8317004e-05, 0.005026085, -0.17149556, 0.01...",...,"[Microsoft Access, Microsoft Visio, communicat...","[perform political negotiation, communication,...","[-0.002798966104, -0.0121953876, -0.0056570900...","[Cisco, communication, prepare presentation ma...",1891,"[-0.008492585, 0.01829961, -0.14708278, -0.023...","[-16.205248, 43.174324, 21.345741]","[-11.809573, 43.81845, 23.515043]","[30.6453, 33.45808, 27.147327]","[-1.7013483, 2.38901, -25.264746]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2479,99416532,RANK: SGT/E-5 NON- COMMISSIONED OFFIC...,"<div class=""fontsize fontface vmargins hmargin...",AVIATION,"[Secret Clearance, Stock Control, Management, ...",5533,"[follow stock control instructions, operations...","[communication, follow stock control instructi...","[0.0049826736, 0.0045687603, -0.19545835, -0.0...","[0.0075103026, -0.0060989116, -0.19636096, -0....",...,"[communication, leadership principles, manage ...","[shape corporate culture, perform political ne...","[-0.0053012248000000005, 0.0435551146, 0.02095...","[communication, leadership principles, manage ...",5419,"[0.0022090778, 0.037456203, -0.17540114, -0.02...","[-14.031494, -40.324745, -15.045181]","[-8.435943, -41.268055, -15.073323]","[46.318626, -23.412395, -9.716426]","[-9.766693, -41.344658, -14.625249]"
2480,24589765,"GOVERNMENT RELATIONS, COMMUNICATIONS ...","<div class=""fontsize fontface vmargins hmargin...",AVIATION,"[arbitration, agency, budgets, Budget, continu...",7108,"[examine budgets, update budget, continuous im...","[Microsoft Visio, computer graphics, continuou...","[0.04153785, 0.038161203, -0.16648234, -0.0115...","[0.048209656, 0.025236994, -0.15883973, -0.005...",...,"[Microsoft Visio, architectural design, commun...","[improve business processes, communication, ri...","[-0.0433943807, 0.010261498, -0.00509086999999...","[Microsoft Visio, architectural design, commun...",2181,"[0.0048152753, 0.035498492, -0.1639306, 0.0078...","[-17.604424, 48.284046, 19.870918]","[-18.579397, 47.64536, 17.187214]","[41.544235, -31.380987, 49.063507]","[-20.233868, 47.91815, 17.69929]"
2481,31605080,GEEK SQUAD AGENT Professional...,"<div class=""fontsize fontface vmargins hmargin...",AVIATION,"[Active Directory, Hardware, Customer Service,...",2020,"[hardware materials, customer service, manage ...","[assemble windows, customer service, hardware ...","[0.010476048, 0.028934365, -0.16972545, 0.0036...","[0.010129859, 0.025989288, -0.16765723, 0.0025...",...,"[assemble windows, communication, customer ser...","[project management, perform data analysis, id...","[0.022557768, -0.057272525, 0.0095303999999999...","[communication, identify process improvements,...",6957,"[0.038275912, -0.04439795, -0.12975419, -0.030...","[-28.97638, 22.674717, 8.510891]","[-28.395866, 21.921257, 9.84287]","[55.829487, 26.824966, 17.281824]","[-27.989061, -33.1997, -35.8058]"
2482,21190805,PROGRAM DIRECTOR / OFFICE MANAGER ...,"<div class=""fontsize fontface vmargins hmargin...",AVIATION,"[Adobe, CPR, Customer Service, Customer Care, ...",5074,"[customer service, maintain customer service, ...","[Microsoft Access, chair a meeting, customer s...","[-0.013092378, 0.055586472, -0.17801957, -0.01...","[-0.006703326, 0.049669117, -0.16404499, -0.01...",...,"[Microsoft Access, communication, customer ser...","[information confidentiality, ethics, communic...","[0.027551798, -0.041949463299999996, 0.0020413...","[Microsoft Access, communication, customer ser...",18145,"[0.020848472, 0.0077196537, -0.16200365, -0.00...","[-14.545741, 34.686108, 35.914818]","[0.06174561, 23.698893, 36.988125]","[36.487293, 7.5631285, 30.039572]","[-1.0762104, 20.694794, 42.01217]"
2483,37473139,STOREKEEPER II Professional Sum...,"<div class=""fontsize fontface vmargins hmargin...",AVIATION,"[Architectural Drafting, AutoCAD, Customer Ser...",5234,"[create architectural sketches, customer servi...","[advise on safety measures, advise supervisors...","[-0.036120985, 0.033106253, -0.17913961, -0.03...","[-0.021321548, 0.018513214, -0.17295599, -0.02...",...,"[communication, follow written instructions, m...","[select material to process, operate material ...","[0.045548919, -0.041604777999999995, 0.0224046...","[communication, follow written instructions, m...",190,"[0.024227371, -0.023091564, -0.15055132, 0.006...","[-39.536102, 6.672747, 13.192839]","[-28.853933, 9.680478, 21.774]","[37.75789, -34.40652, 23.263376]","[-32.03213, 10.277985, 21.211618]"

In [13]:
df.to_parquet('processed/dim_reduced.parquet')