In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import ast
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
import helpers
import ollama

#### Get ESCO embeddings

In [3]:
esco = pd.read_csv('datasets/skills_en.csv')

In [4]:
esco_skills = esco['preferredLabel'].tolist()

In [5]:
response = ollama.embed(model="nomic-embed-text", input=esco_skills)

In [6]:
esco['embeddings'] = response['embeddings']

In [7]:
esco[['preferredLabel', 'embeddings']]

,preferredLabel,embeddings
0,manage musical staff,"[-0.054591812, -0.018804703, -0.17031825, -0.0..."
1,supervise correctional procedures,"[0.048651647, 0.023129402, -0.14121306, -0.031..."
2,apply anti-oppressive practices,"[0.042062778, 0.018910391, -0.16224517, -0.035..."
3,control compliance of railway vehicles regulat...,"[-0.020243065, -0.01827101, -0.17690042, 0.008..."
4,identify available services,"[-0.069251984, -0.0001897157, -0.15665601, -0...."
...,...,...
13934,remediate healthcare user's occupational perfo...,"[-0.01614617, 0.00750463, -0.18048497, -0.0251..."
13935,install transport equipment lighting,"[-0.049296044, 0.03540551, -0.18445863, -0.021..."
13936,natural language processing,"[0.026312111, 0.021747442, -0.11412781, -0.073..."
13937,coordinate construction activities,"[-0.009615241, 0.0053697606, -0.16515373, -0.0..."
13938,position guardrails and toeboards,"[0.005949474, 0.06837154, -0.19821174, 0.03050..."

In [ ]:
esco.to_parquet('processed/esco_skills.parquet', index=False)

In [ ]:
esco = pd.read_parquet('processed/esco_skills.parquet')

#### Preprocessing Resume

In [ ]:
resume = pd.read_csv('datasets/Resume.csv')

In [ ]:
resume

In [ ]:
resume_w_skills = helpers.get_list(data=resume, 
                                   col='Resume_str',
                                   doc_type='resume', 
                                   max_workers=10,
                                   model="mistral:instruct")

In [ ]:
resume_w_skills.to_parquet('processed/resume_w_skills.parquet', index=False)

In [ ]:
resume = pd.read_parquet('processed/resume_w_skills.parquet')

In [ ]:
resume = helpers.fill_missing_skills(resume, esco)

In [ ]:
resume

In [ ]:
resume['length'] = resume['Resume_str'].str.len()

In [ ]:
resume_matched = helpers.match_all_skills_con(resume, esco, threshold=0.8)

In [ ]:
resume_matched

In [ ]:
resume_matched.to_parquet('processed/resume_matched.parquet', index=False)

In [ ]:
resume_matched = pd.read_parquet('processed/resume_matched.parquet')

In [ ]:
resume_matched = pd.read_parquet('processed/resume_embeddings.parquet')

##### Combined calculations

In [ ]:
resume_matched = helpers.average_skills(resume_matched, esco)

In [ ]:
resume_matched['matched_skills_ordered'] = resume_matched['matched_skills'].apply(lambda x: sorted(set(x)))

In [ ]:
skill_embeddings = helpers.embed_skills_list(resume_matched['matched_skills'].tolist())

In [ ]:
skill_embeddings_ordered = helpers.embed_skills_list(resume_matched['matched_skills_ordered'].tolist())

In [ ]:
resume_matched['skill_embeddings'] = skill_embeddings['embeddings']

In [ ]:
resume_matched['skill_embeddings_ordered'] = skill_embeddings_ordered['embeddings']

In [ ]:
resume_matched

In [ ]:
resume_matched.to_parquet('processed/resume_embeddings.parquet', index=False)

In [14]:
resume_matched = pd.read_parquet('processed/resume_embeddings.parquet')

In [15]:
resume_matched

,ID,Resume_str,Resume_html,Category,extracted_skills,length,matched_skills,matched_skills_ordered,skill_embeddings,skill_embeddings_ordered,avg_skill_embedding
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR,"[Accounting, Ads, Advertising, Analytical skil...",5442,"[accounting, create advertisements, outdoor ad...","[accounting, company policies, conduct public ...","[-0.051119804, 0.051380936, -0.1956489, -0.000...","[-0.028823888, 0.056566164, -0.19899392, -0.00...","[0.0002473207458333337, 0.03493942622916666, -..."
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR,"[Adobe Photoshop, ADP, Asset Management, brand...",5572,"[Adobe Photoshop, asset management, maintain c...","[Adobe Illustrator, Adobe Photoshop, asset man...","[-0.013715399, 0.01982399, -0.15967667, 0.0198...","[-0.02063493, 0.030683268, -0.16921557, 0.0126...","[0.002284706435294118, 0.01609132022352941, -0..."
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR,"[Recruiting, FMLA/EEO/FLSA, HRIS Development, ...",7720,"[recruit members, foreign affairs policy devel...","[Microsoft Access, desktop publishing, foreign...","[-0.037161566, 0.0036097213, -0.19848743, -0.0...","[0.0076125017, 0.01415186, -0.17561796, -0.009...","[-0.0002954738888888898, 0.02081807622222222, ..."
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR,"[Type 50 wpm and 10-Key by touch, Microsoft pr...",2855,"[personnel management, customer service, resol...","[customer service, personnel management, resol...","[-0.004071229, -0.0062129777, -0.16848274, -0....","[-0.0024955925, -0.005882781, -0.17091864, -0....","[0.007837255066666667, 0.0018740463333333332, ..."
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR,"[ADA, ADP, art, agency, benefits, Benefits Adm...",9172,"[create artwork, coaching techniques, coaching...","[Microsoft Access, Microsoft Visio, coaching t...","[0.008319367, 0.02057786, -0.17201392, 0.01393...","[4.8317004e-05, 0.005026085, -0.17149556, 0.01...","[0.00895575635652174, 0.013967274808695652, -0..."
...,...,...,...,...,...,...,...,...,...,...,...
2479,99416532,RANK: SGT/E-5 NON- COMMISSIONED OFFIC...,"<div class=""fontsize fontface vmargins hmargin...",AVIATION,"[Secret Clearance, Stock Control, Management, ...",5533,"[follow stock control instructions, operations...","[communication, follow stock control instructi...","[0.0049826736, 0.0045687603, -0.19545835, -0.0...","[0.0075103026, -0.0060989116, -0.19636096, -0....","[0.007711735449999999, 0.005379060733333334, -..."
2480,24589765,"GOVERNMENT RELATIONS, COMMUNICATIONS ...","<div class=""fontsize fontface vmargins hmargin...",AVIATION,"[arbitration, agency, budgets, Budget, continu...",7108,"[examine budgets, update budget, continuous im...","[Microsoft Visio, computer graphics, continuou...","[0.04153785, 0.038161203, -0.16648234, -0.0115...","[0.048209656, 0.025236994, -0.15883973, -0.005...","[0.013527077672727272, 0.028311003981818184, -..."
2481,31605080,GEEK SQUAD AGENT Professional...,"<div class=""fontsize fontface vmargins hmargin...",AVIATION,"[Active Directory, Hardware, Customer Service,...",2020,"[hardware materials, customer service, manage ...","[assemble windows, customer service, hardware ...","[0.010476048, 0.028934365, -0.16972545, 0.0036...","[0.010129859, 0.025989288, -0.16765723, 0.0025...","[0.025738319725, 0.032416258287500006, -0.1611..."
2482,21190805,PROGRAM DIRECTOR / OFFICE MANAGER ...,"<div class=""fontsize fontface vmargins hmargin...",AVIATION,"[Adobe, CPR, Customer Service, Customer Care, ...",5074,"[customer service, maintain customer service, ...","[Microsoft Access, chair a meeting, customer s...","[-0.013092378, 0.055586472, -0.17801957, -0.01...","[-0.006703326, 0.049669117, -0.16404499, -0.01...","[-0.003938775142857142, 0.026151056, -0.158061..."
2483,37473139,STOREKEEPER II Professional Sum...,"<div class=""fontsize fontface vmargins hmargin...",AVIATION,"[Architectural Drafting, AutoCAD, Customer Ser...",5234,"[create architectural sketches, customer servi...","[advise on safety measures, advise supervisors...","[-0.036120985, 0.033106253, -0.17913961, -0.03...","[-0.021321548, 0.018513214, -0.17295599, -0.02...","[-0.0028159249666666656, 0.019260893350000002,..."

#### Preprocess dice

In [ ]:
dice = pd.read_csv('datasets/dice_com-job_us_sample.csv')

In [ ]:
dice

In [ ]:
dice['skills'] = dice['skills'].fillna('')

In [ ]:
dice['skills'] = dice['skills'].str.lower().str.strip()

In [ ]:
dice[dice['skills'].str.contains('see')]

In [ ]:
dice[~dice['skills'].str.contains('see')]['skills']

In [ ]:
dice_w_skills = helpers.get_list(data=dice, 
                                 col='jobdescription', 
                                 doc_type='job', 
                                 max_workers=10,
                                 model="mistral:instruct")

In [ ]:
dice_w_skills

In [ ]:
dice_w_skills.to_parquet('processed/dice_job_descriptions_with_skills.parquet', index=False)

In [ ]:
dice_w_skills = pd.read_parquet('processed/dice_job_descriptions_with_skills.parquet')

In [ ]:
dice_w_skills = helpers.fill_missing_skills(data=dice_w_skills,
                                           skills_col='skills',
                                           doc_type='job',
                                           max_workers=3)

In [ ]:
dice_w_skills

In [ ]:
matched = helpers.match_all_skills_con(dice_w_skills, esco, threshold=0.8)

In [ ]:
matched.to_parquet('processed/dice_job_descriptions_matched.parquet', index=False)

In [ ]:
jobs_matched = pd.read_parquet('processed/dice_job_descriptions_matched.parquet')

In [ ]:
jobs_matched['matched_skills_ordered'] = jobs_matched['matched_skills'].apply(lambda x: sorted(set(x)))

In [ ]:
skill_embeddings = helpers.embed_skills_list(jobs_matched['matched_skills'].tolist())

In [ ]:
skill_embeddings_ordered = helpers.embed_skills_list(jobs_matched['matched_skills_ordered'].tolist())

In [ ]:
jobs_matched['skill_embeddings'] = skill_embeddings['embeddings']

In [ ]:
jobs_matched['skill_embeddings_ordered'] = skill_embeddings_ordered['embeddings']

In [ ]:
matched

In [ ]:
jobs_matched.to_parquet('processed/dice_job_descriptions_embeddings.parquet', index=False)

In [ ]:
matched = pd.read_parquet('processed/dice_job_descriptions_embeddings.parquet')

In [ ]:
matched

In [ ]:
matched_avg = helpers.average_skills(matched, esco)

In [ ]:
matched_avg

In [ ]:
matched_avg.to_parquet('processed/dice_job_descriptions_embeddings.parquet', index=False)